### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by solnou** [Esc-IngComp-UNC/staff-access-monitoring-system#3]
Gather and document the user requirements for the staff access monitoring system. This includes understanding the needs of the users and defining the required functionalities.

**Comment by francobottini99** [comment]
Several points to review regarding [requirements documentation](https://github.com/Esc-IngComp-UNC/staff-access-monitoring-system/blob/development/Issues_resources/Issue_%233.pdf):

- The document mentions requirements that are outside the scope of the PPS. The following sections are outside this first stage of development and are subject to possible expansion in the event of continued development in a future PI:
  - User profiles to which different permissions, groups, etc. can be assigned.
  - Remote firmware updates via Ethernet.
  - Support for multiple terminals and easy integration of new terminals.
  - Alert systems for detecting anomalies.

- The requirement to connect to the Internet via Ethernet is mentioned, however, the [hardware definition document](https://github.com/Esc-IngComp-UNC/staff-access-monitoring-system/blob/development/Issues_resources/Issue_%231_%232_%236.pdf) does not implement the necessary support for this functionality.

- Two different types of users are characterized, but the [front-end specification](https://github.com/Esc-IngComp-UNC/staff-access-monitoring-system/blob/development/Issues_resources/Issue_%234.pdf) does not establish how this will be handled.

- It is necessary to differentiate outputs from inputs, how is this going to be done? Is additional hardware necessary?

- It is necessary to break down the requirements further, since they are presented in a very general way. Well-defined requirements will facilitate the later stages of development.

**Comment by GabrielEValenzuela** [comment]
Hi @solnou and @Jorgear27,

Could you please add the content of the PDF mentioned by @francobottini99 as an issue? This way, the documentation will be more accessible and organized within our issue tracking system. By keeping documentation separate from the code, we ensure that the code remains clean and maintainable, while all relevant information is easily accessible in a centralized location.

Thanks!

**Comment by solnou** [comment]
27/09/2024 We have removed some requirements that are beyond the scope of the project. Some issues need to be detailed further. We will continue working on this.

Spend 🍅 1+

**Comment by Jorgear27** [comment]
28/09/2024  We defined the requirements in a more detailed way and improved the documents related to them.

Spent 🍅 3+

**Comment by solnou** [comment]
Add the Manager user. We improved this delivery, it is pending review before passing the document to the epic
[Doc to review](https://drive.google.com/file/d/1biecirlGkMr_SwMW9-C3o1qqph5-n86e/view?usp=sharing)
Spent 🍅 1+

**Comment by valentinrb1** [comment]
We leave you the [file](https://drive.google.com/file/d/1_NCdzBJgOVnjnTVlt6Jq3NmLqcA8AZud/view?usp=drive_link) with some corrections.

**Comment by Jorgear27** [comment]
01/10/2024 We re-organized the system users based on privileges and assign them their corresponding responsabilities in the [Requirements Document](https://drive.google.com/file/d/1biecirlGkMr_SwMW9-C3o1qqph5-n86e/view?usp=sharing)

Spent 🍅 2+

**Comment by francobottini99** [comment]
The corrections are good. This issue is closed, from now on work on the issue of the requirements on the main issue #9. For particular requirements open new issues.
