### ISSUE TITLE
Front-End Specification

### ISSUE THREAD

**Issue by solnou** [Esc-IngComp-UNC/staff-access-monitoring-system#4]
Design a simple and understandable wireframe for the front-end of the web interface that will be used by administrators and staff to interact with the access monitoring system. The wireframe should providing a visual guide with key elements for the development of the front-end.

**Comment by valentinrb1** [comment]
Some aspects to review in the [Front-End design](https://github.com/Esc-IngComp-UNC/staff-access-monitoring-system/blob/development/Issues_resources/Issue_%234.pdf):

- The implementation of a section for the login by the administrator is mentioned, however, its design is not exposed.
- How will the administrator accounts be managed? Is it just one? Can new ones be added? If so, on which screen?
- A page is required to display the users loaded in the system.
- The design of the section to display the movements, lacks a column that specifies the type, that is, if it is an entry or an exit.
- The page where the registration of a user is proposed is not well specified, how is the logic of its operation?
- If you want to delete a user, what is the process to follow? And if you want to modify one?

It is recommended to improve the presentation of the wireframes and better explain their operation, giving a better vision of the design proposal.

**Comment by francobottini99** [comment]
It is also necessary to specify in the [document](https://github.com/Esc-IngComp-UNC/staff-access-monitoring-system/blob/development/Issues_resources/Issue_%234.pdf) the technologies that will be used for the development of the front-end.

**Comment by GabrielEValenzuela** [comment]
Same comment that #3

**Comment by Jorgear27** [comment]
28/09/2024 We updated the Front-End design, and detailed each functionality and screen included in the Wireframe.

Spent 🍅 4+

**Comment by solnou** [comment]
29/09/2024 We improved this delivery, it is pending review before passing the document to the epic
[Doc for review](https://drive.google.com/file/d/1uHhHJbpOSla9bhx3wDFr5R6w9nk0c7gf/view?usp=sharing)
Spent 🍅 3+

**Comment by valentinrb1** [comment]
Good morning.

Well, now the scenarios are better covered.

Corrections:

For the login screen, it is not necessary to have two different sections. You can have a single screen and then differentiate whether the user is an "administrator" or "manager" by adapting the accesses depending on their user privilege, in this way we unify the login front-end.

Add a navigation system for the main screen. It is not clear how one accesses these different views.

Consider that a user with higher privileges contains all the privileges of a user with lower privileges. For example, in your case a manager can also manage the user load.

You can generalize the Administrator Manager screen by adding the option to be able to add another management if needed. This can be achieved by adding a column that indicates the privilege level. This allows new privilege levels in the system in the future.

In the User Registration screen we should capture more user data, such as last name, phone number, address, etc. since the objective of the system is to have access control. Also, a username field is not necessary in this case since the user will never access the system, their information is simply needed to be able to register entries/exits.

Add the wireframe to register new administrators.

**Comment by solnou** [comment]
01/10/2024 we review the corrections

[New Doc to review](https://drive.google.com/file/d/199G11wLXLL7Gw8mZcR8uZ0bea18CNF5e/view?usp=sharing)

Spent 🍅 5+

**Comment by valentinrb1** [comment]
We leave you with one last [correction](https://drive.google.com/file/d/1RyWtjAqCFvBIIkU_GiMy9OiVUW4zPOW5/view?usp=drive_link).

Once you correct that, we move the issue to final review.

**Comment by Jorgear27** [comment]
01/10/2024 We corrected the title-naming mistake

The [document](https://drive.google.com/file/d/199G11wLXLL7Gw8mZcR8uZ0bea18CNF5e/view?usp=sharing) is uploaded to the epic.


Spent 🍅 1+

**Comment by GabrielEValenzuela** [comment]
I will make a review of this issue ASAP

**Comment by GabrielEValenzuela** [comment]
# Review

Great work team! I like the approach, please considered the option of expose the passwords, even they are encrypted, we should avoid show them in the dashboard.

Another improvement, we can improve the name of the administrators, making a more hierarchy model.

I think these changes and minimal and we can close this task and refine it in later tasks.

Again, amazing work!
