### ISSUE TITLE
Research Real Time Clock (RTC)

### ISSUE THREAD

**Issue by valentinrb1** [Esc-IngComp-UNC/staff-access-monitoring-system#6]
We recommend that you investigate RTCs to improve system performance.
Although the ESP32 has an RTC, it has several disadvantages compared to external RTCs, such as not having an internal battery, which means that it loses synchronization with the time.
As a recommendation: DS3231 module.

**Comment by francobottini99** [comment]
What is stated in the [document](https://github.com/Esc-IngComp-UNC/staff-access-monitoring-system/blob/development/Issues_resources/Issue_%231_%232_%236.pdf) is correct, however, to maintain order, the results of your research should be exposed in this issue. It is also emphasized that the results of the research should not be mixed with the specification documents. The results of a research issue can be written in a document and then referenced, or if the result is not very extensive, it can be expressed as a comment on the issue.

**Comment by Jorgear27** [comment]
## Results:

Although the ESP32 microcontroller already has an integrated RTC, it may experience synchronization problems due to the lack of an internal battery as a power source. This is the main reason why we decided to use the DS3231 module. It is a low-cost, highly accurate I2C real-time clock with an integrated temperature-compensated crystal oscillator (TCXO) and crystal. The device incorporates a battery input and maintains accurate timekeeping even when the main power to the device is interrupted.

We highlight the following aspects:

1. **Temperature Compensation**: the temperature-compensated crystal oscillator (TCXO) in the DS3231 ensures accuracy over a wide range of temperatures, which is a critical factor, especially considering that we are in a city with wide temperature ranges and constant changes. 

2. **I2C Communication**: the DS3231 communicates via the I2C protocol, which simplifies integration with the ESP32. 

3. **Time Accuracy**: the DS3231 has an accuracy of ±2 minutes per year, which is far better than the ESP32's internal RTC.

4. **Backup Battery**: Expand on the advantage of the backup battery, explaining how it ensures the system keeps track of time during power outages or resets, making it highly reliable.

More specifications about the DS3231 module can be found in the [Hardware Specification document](https://github.com/Esc-IngComp-UNC/staff-access-monitoring-system/blob/development/Issues_resources/Issue_%231.pdf)

**Comment by francobottini99** [comment]
God job !
